### ISSUE TITLE
bug: checking for updates yields a 404 error

### ISSUE THREAD

**Issue by marrie** [aaclause/basiliskLLM#167]
# steps
1. launch the app
2. click help
3. clickupdate
This is when the following error appears.
Message  dialog  Error checking for updates: Client error '404 Not Found' for url 'https://api.github.com/repo/aaclause/basiliskLLM/releases/latest'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
OK  button
 I'm using nvda 24.2 and BasiliskLLM 0.1a4 on Windows 11 23H2 (AMD64) build 22631.4037

Thanks.

**Comment by clementb49** [comment]
The current issue arises from the lack of a stable release. We are currently in the pre-release phase.  
To address this, I recommend changing the default release channel from "stable" to "beta" for the next release. This will ensure users are aware that they are using a pre-release version. Once a stable release is ready, we can revert the default channel back to "stable."
